// <auto-generated />
using System;
using BiletSinema.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiletSinema.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611063526_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiletSinema.Models.Diziler", b =>
                {
                    b.Property<int>("DiziNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiziNo"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KategoriNo")
                        .HasColumnType("int");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiziNo");

                    b.HasIndex("KategoriNo");

                    b.ToTable("Diziler");
                });

            modelBuilder.Entity("BiletSinema.Models.Filmler", b =>
                {
                    b.Property<int>("FilmNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmNo"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KategoriNo")
                        .HasColumnType("int");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmNo");

                    b.HasIndex("KategoriNo");

                    b.ToTable("Filmler");
                });

            modelBuilder.Entity("BiletSinema.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriNo"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriNo");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("BiletSinema.Models.Tiyatrolar", b =>
                {
                    b.Property<int>("TiyatroNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiyatroNo"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KategoriNo")
                        .HasColumnType("int");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TiyatroNo");

                    b.HasIndex("KategoriNo");

                    b.ToTable("Tiyatrolar");
                });

            modelBuilder.Entity("BiletSinema.Models.Diziler", b =>
                {
                    b.HasOne("BiletSinema.Models.Kategori", "kategori")
                        .WithMany("Diziler")
                        .HasForeignKey("KategoriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategori");
                });

            modelBuilder.Entity("BiletSinema.Models.Filmler", b =>
                {
                    b.HasOne("BiletSinema.Models.Kategori", "kategori")
                        .WithMany("Filmler")
                        .HasForeignKey("KategoriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategori");
                });

            modelBuilder.Entity("BiletSinema.Models.Tiyatrolar", b =>
                {
                    b.HasOne("BiletSinema.Models.Kategori", "kategori")
                        .WithMany("Tiyatrolar")
                        .HasForeignKey("KategoriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategori");
                });

            modelBuilder.Entity("BiletSinema.Models.Kategori", b =>
                {
                    b.Navigation("Diziler");

                    b.Navigation("Filmler");

                    b.Navigation("Tiyatrolar");
                });
#pragma warning restore 612, 618
        }
    }
}
